spring.application.name=QuickBite

spring.datasource.url=jdbc:mysql://localhost:3306/QuickBite
spring.datasource.username=root
spring.datasource.password=raj1410
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect